config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'
  get 'errors/unacceptable'
  get 'errors/internal_error'
  devise_for :users
  root to: 'pages#home'

  resources :complaints

  resources :cities, only: [:show]

  resources :types, only: [:show]

  resources :users # Masha created thos route to be able to see the profile that is does not belong to the current user

  post "upvote", to: "complaints#upvote", as: :upvote

  post 'basket', to: 'users#basket', as: :basket

  get 'profile', to: 'pages#profile', as: :profile
  #get 'user_profile', to: 'pages#user_profile', as: :user_profile
  get 'supermap', to: 'pages#supermap', as: :supermap

  get "/complaints/:complaint_id/mail", to: 'pages#mail', as: :mail

  get 'emails', to: 'pages#emails', as: :emails

  get 'create_email', to: 'pages#create_email', as: :create_email

  get "/404", to: "errors#not_found"
  get "/422", to: "errors#unacceptable"
  get "/500", to: "errors#internal_error"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :complaints
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :province
  has_many :complaints
  has_many :users
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  mount_uploader :picture, PictureUploader
  belongs_to :user
  belongs_to :category
  belongs_to :type
  belongs_to :city
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/province.rb
class Province < ApplicationRecord
  belongs_to :region
  has_many :cities
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :provinces
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :complaints
end

app/models/user.rb
class User < ApplicationRecord
  has_many :complaints
  belongs_to :city

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :city_id, :profession, :mayor])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :city_id, :profession, :mayor])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
    @city = City.find(current_user.city_id)
  end
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    unless params[:query] == "" || params[:query].nil?
      @location = params[:query]
    else
      @location = "Madrid"
    end
    create_map(@location)

    @complaint = Complaint.new

    # this make us use the current location so dont comment it out.
    @complaints = Complaint.near(@location, 20)

    @markers = @complaints.map do |complaint|
      {
        lat: complaint.latitude,
        lng: complaint.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { complaint: complaint })
      }
    end
  end

  def show
    @complaint = Complaint.find(params[:id])
  end

  def new
    @complaint = Complaint.new
  end

  def create
    @complaint = Complaint.new(complaint_params)
    @complaint.upvote = 1
    @complaint.user = current_user

    @complaint.category = Category.find(params[:complaint][:category_id])
    @complaint.type = Type.find(params[:complaint][:type_id])
    address_to_city = Geocoder.search(@complaint.address)[0].data["address"]["city"]
    City.create(name: address_to_city, province: Province.last)
    @complaint.city = City.find_by_name(address_to_city)
    if @complaint.save
      redirect_to complaints_path, notice: "Complaint was succesfully created!"
    else
      render :new
    end
  end

  def destroy
    @complaint = Complaint.find(params[:id])
    @complaint.destroy
    redirect_to profile_path
  end

  def upvote
    @complaint = Complaint.find(params[:complaint])
    @complaint.upvote += 1
    @complaint.save

    if @complaint.save
      respond_to do |format|
        format.html { redirect_to complaints_path }
        format.js  # <-- will render `app/views/complaints/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'complaints/index' }
        format.js  # <-- idem
      end
    end
  end

  private

  def create_map(location)
    inter = Geocoder.search(location)
    @results = inter.first.coordinates if inter.first.present?
    @complaints = Complaint.near(location, 20)
  end

  def complaint_params
    params.require(:complaint).permit(:description, :picture, :address, :category_id, :type_id)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
      format.json { render json: { error: "Resource not found" }, status: 404 }
    end
  end

  def unacceptable
    respond_to do |format|
      format.html { render status: 422 }
      format.json { render json: { error: "Params unacceptable" }, status: 422 }
    end
  end

  def internal_error
    respond_to do |format|
      format.html { render status: 500 }
      format.json { render json: { error: "Internal server error" }, status: 500 }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def profile
    @user = current_user
  end

  def create_email
    complaint = Complaint.find(params[:complaint])
    complaint.favorite = false
    complaint.save
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController

  def index
  end

  def show
    @type = Type.find(params[:id])
  end

  def new
  end

  def create
  end

  def delete
  end

  def edit
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def basket
    @complaint = Complaint.find(params[:complaint])
    @complaint.favorite = true
    if @complaint.save
      if params[:city].present?
        redirect_to city_path(params[:city].to_i), notice: "Complaint was succesfully added!"
      elsif params[:type].present?
        redirect_to type_path(params[:type].to_i), notice: "Complaint was succesfully added!"
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/cities/_showcity.html.erb
<div class="modal fade" id="showModal_<%= complaint.id %>" tabindex="-1" role="dialog" aria-labelledby="showModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="show-form">
        <div class="complaint-head">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h6 class="modal-title" id="exampleModalLongTitle">Complaint details</h6>
        </div>

        <p><strong><%= complaint.address %></strong></p>
        <div class="items">
          <h6 id="category"><%= complaint.category.name %></h6>
          <h6 id="type"><%= complaint.type.name %></h6>
        </div>
        <p id="description"><%= complaint.description %></p>
        <p><strong>Author : </strong><%= link_to complaint.user.name, user_path(complaint.user) %></p>
        <p><strong>Reported on : </strong><%= complaint.created_at %></p>
        <!-- The photo is displayed below -->
        <div class="upvote-complaints">
          <% if complaint.picture.present? %>
          <div class="complaint_image">
            <%= cl_image_tag(complaint.picture, crop: :fill) %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="upvote">
        <div class="col-4 upvote-complaints">
          <i class="fas fa-thumbs-up" class="blue-font"></i>
          <%= complaint.upvote %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/cities/show.html.erb
<div id="city-container">
  <h1><%= @city.name %></h1>
  <div id="city-type-filter">
    <h3>filter your complaint by type:</h3>
</div>
  </div>
  <div class="margins-type">
    <span class="tag type typeColor" >
      <%= link_to type_path(Type.find_by(name: 'Bridge')) do %>
      <%= "Bridges" %>
      <% end %>
    </span>
    <span class="tag type typeColor">
      <%= link_to type_path(Type.find_by(name: 'Park')) do %>
      <%= "Parks" %>
      <% end %>
    </span>
    <span class="tag type typeColor">
      <%= link_to type_path(Type.find_by(name: 'Road')) do %>
      <%= "Roads" %>
      <% end %>
    </span>
    <span class="tag type typeColor">
      <%= link_to type_path(Type.find_by(name: 'Public Bulding')) do %>
      <%= "Public Buldings"  %>
      <% end %>
    </span>
  </div>
  <div class="madrid-map">
    <%= image_tag('MadridMap.png', width: 360, height: 250) %>
  </div>



  <div>
    <div class="c-t-complaints-tilte">
      <h3>Complaints:</h3>
    </div>
    <div>
      <% @city.complaints.each do |complaint| %>
        <div class="complaint-container">
          <hr class="separator">
          <div class="row">
            <div class="col-8" >
              <%= link_to complaint_path(complaint), "data-toggle" => "modal", "data-target" => "#showModal_#{complaint.id}" do %>
                <p> "<%= complaint.description %>" </p>
              <% end %>
            </div>
            <div class="col-4 upvote-complaints">
              <i class="fas fa-thumbs-up" class="blue-font"></i>
              <%= complaint.upvote %>
              <div class="type tagShow">
                <%= complaint.type.name %>
              </div>
              <div class="c-t-plus-btn">
                  <%= link_to basket_path(complaint: complaint, city: @city), method: :post do %>
                    <%= image_tag('ADDBUTTON.png', width: 20, height: 20) %>
                  <% end %>
              </div>
            </div>
          </div>
         <%= render 'showcity', complaint: complaint  %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/complaints/_info_window.html.erb
<h5><%= link_to complaint.description, complaint_path(complaint), "data-toggle" => "modal", "data-target" => "#showModal_#{complaint.id}"  %></h5>

<div class="upvote">
  <div class="index-upvoke upvote-complaints" id="<%= complaint.id %>" >
    <div class="tag">
      <%= complaint.type.name %>
    </div>
    <div>
    <%= link_to upvote_path(complaint: complaint),method: :post, remote: :true do %>
    <%= render 'likes', complaint: complaint %>
    <% end %>
  </div>
  </div>
</div>

app/views/complaints/_likes.html.erb
<%= link_to upvote_path(complaint: complaint), method: :post, remote: true do %>
  <i class="fas fa-thumbs-up" class="blue-font"></i>
<% end %>
<span data-upvote="complaint-<%= complaint.id %>" id=><%= complaint.upvote %>
</span>

app/views/complaints/_show.html.erb
<!-- <h1>Complaints#show</h1>
<p>Find me in app/views/complaints/show.html.erb</p>
<%= complaint.id  %>
 -->
<div class="modal fade" id="showModal_<%= complaint.id %>" tabindex="-1" role="dialog" aria-labelledby="showModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="show-form">
        <div class="complaint-head">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h6 class="modal-title" id="exampleModalLongTitle">Complaint details</h6>
        </div>

        <p class="complaint-address"><i class="fas fa-map-marker-alt"></i> <strong><%= complaint.address %></strong></p>
        <div class="items">
          <h6 id="category"><%= complaint.category.name %></h6>
          <h6 id="type"><%= complaint.type.name %></h6>
        </div>
        <p id="description"><%= complaint.description %></p>
        <div class="description-date">
        <p><strong>Author : </strong><%= link_to complaint.user.name, user_path(complaint.user) %></p>
        <p><strong>Reported on : </strong><%= complaint.created_at %></p>
        </div>
        <!-- The photo is displayed below -->
        <div class="upvote-complaints">
          <% if complaint.picture.present? %>
          <div class="complaint_image">
            <%= cl_image_tag(complaint.picture, crop: :fill) %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="upvote">
        <div class="col-4 upvote-complaints complaint-icon" id="<%= complaint.id %>" >
          <%= link_to upvote_path(complaint:complaint),method: :put, remote: :true do %>
          <%= render 'likes', complaint: complaint %>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/complaints/index.html.erb
<div class="complaint-index-container">

  <div id='location-style'>
   <%= link_to image_tag("EDITICON.png", width: 32, height: 28), root_path %>
    <div id='address-location'>
      <% if params[:query].present? %>
        <p><strong><%= params[:query]  %></strong></p>
      <% else %>
        <p><strong>Madrid</strong>
      <% end %>
    </div>
  </div>

  <div class="index_instruction">
    <p>Click a pin <%= link_to image_tag("PINICON.png", width: 16, height: 20), root_path %> to view complaint:</p>
  </div>
</div>

<div id="map-container">
  <div
  id="map"
  style="width: 100%;
  height: 380px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  <% if @results.present?%>
    data-latitude="<%= @results[0] %>"
    data-longitude="<%= @results[1] %>"
  <% else %>
    data-latitude="40.4165"
    data-longitude="-3.70256"
  <% end %>
  ></div>
</div>

<div class="complaint-index-container" id="complaintBox" style="min-height:600px;">
  <%= link_to "Add a complaint", root_path, class: "btn btn-primary-red square-btn-red",  "data-toggle" => "modal", "data-target" => "#formModal" %>

  <a data-scroll href="#scrollcomplaint">
    <div class="arrow"></div>
  </a>


  <div class="container">
    <h5 id="scrollcomplaint"> Complaints around the area </h5>
    <% @complaints.each do |complaint| %>
      <div class="complaint-container">
        <hr class="separator">
        <div class="row">
          <div class="col-8" >
            <%= link_to complaint_path(complaint), "data-toggle" => "modal", "data-target" => "#showModal_#{complaint.id}" do %>
              <p> "<%= complaint.description %>" </p>
            <% end %>
          </div>
          <div class="col-4 upvote-complaints" id="<%= complaint.id %>" >
              <%= render 'likes', complaint: complaint %>
            <div class="tagShow">
              <%= complaint.type.name %>
            </div>
          </div>
        </div>
        <%= render 'show', complaint: complaint  %>
      </div>
    <% end %>
  </div>
</div>

<!-- Modal for new complaint -->
<div class="modal fade" id="formModal" tabindex="-1" role="dialog" aria-labelledby="formModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" align="center" id="exampleModalLongTitle">Add a complaint</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "shared/form" %>
      </div>
    </div>
  </div>
</div>


<!-- Javascript for scrolling -->
<script>
var toggle = false;
    var img = document.getElementById('imgChange').src;
    var el = document.getElementById('complaintBox');
    function scrollWin(x, y) {
        if (toggle === true) {
            document.getElementById('imgChange').src = '/assets/scroll_arrow.png';
            el.classList.remove('animate');

        } else {
            document.getElementById('imgChange').src = '/assets/scroll_arrow_down.png';
            el.classList.add('animate');

        }
        toggle = !toggle;
    }
  </script>

app/views/pages/_showemail.html.erb
<div class="modal fade" id="showModal_<%= complaint.id %>" tabindex="-1" role="dialog" aria-labelledby="showModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="show-form">
        <div class="complaint-head">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h6 class="modal-title" id="exampleModalLongTitle">Complaint details</h6>
        </div>

        <p><strong><%= complaint.address %></strong></p>
        <div class="items">
          <h6 id="category"><%= complaint.category.name %></h6>
          <h6 id="type"><%= complaint.type.name %></h6>
        </div>
        <p id="description"><%= complaint.description %></p>
        <p><strong>Author : </strong><%= link_to complaint.user.name, user_path(complaint.user) %></p>
        <p><strong>Reported on : </strong><%= complaint.created_at %></p>
        <!-- The photo is displayed below -->
        <div class="upvote-complaints">
          <% if complaint.picture.present? %>
          <div class="complaint_image">
            <%= cl_image_tag(complaint.picture, crop: :fill) %>
          </div>
          <% end %>
        </div>
      </div>
      <div class="upvote">
        <div class="col-4 upvote-complaints">
          <i class="fas fa-thumbs-up" class="blue-font"></i>
          <%= complaint.upvote %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/pages/create_email.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="email-container">
      <h2>EMAIL TOOL</h2>
      <p>Write an email to send to every single citizen who has posted and liked your chosen complaint.
      </p>
    </div>
    <form role="form" method="post" id="reused_form">

      <div class="row row-margins">
        <div class="col-sm-6 form-group">
          <!--             <label for="name">
            Subject:</label> -->
          <input type="text" class="form-control form-control-no-pa" id="name" placeholder="Subject" name="name" required>
        </div>
      </div>
      <div class="row row-margins">
        <div class="col-sm-12 form-group">
          <textarea class="form-control form-control-no-pa" type="textarea" name="comments" id="comments" placeholder="Your message" maxlength="6000" rows="7"></textarea>
          <img src="Dear #{citizen-name}.png" alt="">
        </div>
      </div>
    </form>
  </div>
</div>

<div class="email-container">
  <%= link_to "Send email", emails_path, id: "sweet-alert-demo", class: "btn btn-primary" %>
</div>

app/views/pages/emails.html.erb
<div id="email-container">
  <div id="email-title">
    <h3>Your complaints basket</h3>
    <p>Use this tool to send emails to multiple citizens
    with a single click!</p>
  </div>
  <div id='email-complaints-title'>
    <h6>Complaints you have added:</h6>
  </div>
  <div>
    <% if Complaint.find_by(favorite: true).nil? %>
      <p>You havent added any complaints </p>
    <% else %>
      <% Complaint.where(favorite: true).each do |complaint| %>
        <div class="complaint-container">
          <hr class="separator">
          <div class="row">
            <div class="col-8" >
              <%= link_to complaint_path(complaint), "data-toggle" => "modal", "data-target" => "#showModal_#{complaint.id}" do %>
                <p> "<%= complaint.description %>" </p>
              <% end %>
            </div>
            <div class="col-4">
                <%= link_to create_email_path(complaint: complaint) do %>
                  <%= image_tag("email-icon.png", width: 45, height: 45) %>
                <% end %>
            </div>
          </div>
          <%= render 'showemail', complaint: complaint  %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? && current_user.mayor == true %>
  <div class="homepage-container">
    <div class="presentation">
      <div class="welcome-message">
        <h2>Welcome to</h2>

        <div class="container-intro" id="m-container-intro">
          <h1>Urban</h1>
          <h1 id="display-inline-block" >Feed</h1>
          <div id="m-sub-welcome"><p>Politician</p></div>
        </div>
      </div>
    </div>

    <div class="container-intro">
      <p id = "p-intro">Use our tools to target the maximum amout of citizens!</p>
    </div>

    <p id= tool>Select a tool :</p>

    <div id="actions">
      <%= link_to city_path(current_user.city) do %>
        <%= image_tag('MAPTOOL-ICON.png', width: 150, height: 140) %>
      <% end %>

      <%= link_to emails_path do %>
        <%= image_tag('EMAILTOOL-ICON.png', width: 150, height: 140) %>
      <% end %>

    </div>
  </div>
   <div class="tool-instruction1">
        <p> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Find the most </p> <p>&nbsp; &nbsp; supported complaints</p>
         </div>

   <div class="tool-instruction2">
        <p> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Send emails </p> <p>on your chosen complaints </p>
         </div>
<% else %>

  <div class="homepage-container">
    <div class="welcome-message">
      <h2>Welcome to</h2>
      <div class="container-intro">
        <h1>Urban</h1>
        <h1 id="display-inline-block" >Feed</h1>
      </div>
    </div>
    <div class="container-intro">
      <p>Report incidences on your</p>
      <p>neighbourhood</p>
    </div>
  </div>
    <%= form_tag complaints_path, method: :get do %>
      <div class="form_box home_form">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control-style",
          id: "complaint-address",
          placeholder: " Introduce your location"%>
       <i class="fas fa-map-marker-alt"></i>
        <%= submit_tag "Go!", class: "btn btn-primary square-btn-blue" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/pages/profile.html.erb
<div class="userprofile-container">
  <h2>Your Profile</h2>

  <div id="p-margins">
    <p><strong>Name: </strong><%=@user.name%></p>
    <p><strong>Profession: </strong><%=@user.profession%></p>
    <p><strong>Email: </strong><%=@user.email%></p>
  </div>

  <% unless current_user.mayor == true %>
    <h2>Your complaint history :</h2>
    <% if Complaint.where(user_id:@user.id).count == 0 %>
      <p id = "no-complaint"><em>Sorry, you don't have any complaint 🤔 !</em></p>
    <% else %>
      <div class="profile-info-container">
        <% Complaint.where(user_id:@user.id).each do |complaint| %>
          <div class="complaint-container">
            <hr id="separator-profile">
            <div class="row" id="row-profile">
              <div class="" >
                <div style=text-align="center">
                  <div class="tag">
                    <%= complaint.type.name %>
                  </div>
                  <br>
                  <%= link_to complaint_path(complaint), "data-toggle" => "modal", "data-target" => "#showModal_#{complaint.id}" do %>
                    <p> "<%= complaint.description %>" </p>
                  <% end %>
                </div>
              </div>
              <div class="profile-options-container">
                <p id="thumb-profile"><%= complaint.upvote %><i class="fas fa-thumbs-up" id="blue-thumb-profile"></i></p>
                 <p><%= link_to image_tag("DELETEICON.png", width: 22, height: 28), complaint_path(complaint), method: :delete %></p>
                </div>
                <hr id="separator-profile">
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <h2></h2>
  <% end %>
  </div>

<div class="bottom-links">
  <% if current_user.mayor == true %>
    <p><%= link_to 'Back', city_path(City.first.id) %></p>
  <% else %>
    <p><%= link_to 'Back', complaints_path %></p>
  <% end %>

  <p><%= link_to "log out", destroy_user_session_path, method: :delete%></p>
</div>

app/views/shared/_loginform.html.erb
<div class="signin-form-container">
  <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <div class="masha-form login-form">
      <%= f.input :email,
      required: false,
      autofocus: true,
      placeholder: "email",
      input_html: { autocomplete: "email" } %>
         <i class="fas fa-envelope"></i>
      <%= f.input :password,
      required: false,
      placeholder: "password",
      input_html: { autocomplete: "current-password" } %>
       <div class="">
      <i class="fas fa-lock" id= "initial"></i>
      </div>
    </div>
  </div>
    <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>

</div>

<div class="link-buttons-align">
  <div class="button-align">
    <div class="form-actions">
      <div class="btn-color-signin">
        <%= f.button :submit, "login" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/types/show.html.erb
<div id="city-container">
  <h1><%= current_user.city.name %></h1>
  <div id="city-type-filter">
    <h3>complaints on:  <%= @type.name.downcase %></h3>
  </div>
</div>
  <div class="margins-type">
    <span class="tag type typeColor" >
      <%= link_to type_path(Type.find_by(name: 'Bridge')) do %>
      <%= "Bridges" %>
      <% end %>
    </span>
    <span class="tag type typeColor">
      <%= link_to type_path(Type.find_by(name: 'Park')) do %>
      <%= "Parks" %>
      <% end %>
    </span>
    <span class="tag type typeColor">
      <%= link_to type_path(Type.find_by(name: 'Road')) do %>
      <%= "Roads" %>
      <% end %>
    </span>
    <span class="tag type typeColor">
      <%= link_to type_path(Type.find_by(name: 'Public Bulding')) do %>
      <%= "Public Buldings"  %>
      <% end %>
    </span>
  </div>

  <div class="madrid-map">
    <%= image_tag('MadridMap.png', width: 360, height: 250) %>
  </div>

  <div class="c-t-complaints-container">
    <div class="c-t-complaints-tilte">
      <h3>Complaints:</h3>
    </div>
    <div>
      <% @type.complaints.each do |complaint| %>
      <div class="complaint-container">
        <hr class="separator">
        <div class="row">
          <div class="col-8" >
            <%= link_to complaint_path(complaint), "data-toggle" => "modal", "data-target" => "#showModal_#{complaint.id}" do %>
              <p> "<%= complaint.description %>" </p>
            <% end %>
          </div>
          <div class="col-4 upvote-complaints">
            <i class="fas fa-thumbs-up" class="blue-font"></i>
            <%= complaint.upvote %>
            <div class="c-t-plus-btn">
               <%= link_to basket_path(complaint: complaint, type: @type ), method: :post do %>
                 <%= image_tag('ADDBUTTON.png', width: 20, height: 20) %>
               <% end %>
            </div>
          </div>
        </div>
        <%= render 'showtypes', complaint: complaint  %>
      </div>
      <% end %>
    </div>
  </div>

<script>
  function scrollWin(x, y) {
    window.scrollBy(x, y);
  }
</script>